### ISSUE TITLE
Report/WishList  NullReferenceException

### ISSUE THREAD

**Issue by naaturaz** [SeaSharpe/Implementation#54]
Logged as user: PAMELALALOVIC475670

Clicked on Report, then on WishList and brakes.
WishListsReport.cshtml
Line 17

Clicked on Report, then on Sales brakes too:
SalesReport.cshtml
Line 16

**Comment by pjthomso** [comment]
These features have not been complete yet, Rob is currently working on them but he is also working on events

**Comment by naaturaz** [comment]
OK. So im closing issue until Rob finishes that
